{% set name = "satchip" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/satchip-{{ version }}.tar.gz
  sha256: 37d78953baeade7ea1c6be42a4df5cb3918e39038ca4f0f434afe3d6d58bf377

build:
  entry_points:
    - chiplabel = satchip.chip_label:main
    - chipdata = satchip.chip_data:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - numpy
    - shapely
    - pyproj
    - pystac-client
    - rasterio
    - zarr
    - xarray
    - rioxarray
    - pandas
    - geopandas
    - asf_search
    - hyp3_sdk
    - tqdm

test:
  imports:
    - satchip
  commands:
    - pip check
    - chiplabel --help
    - chipdata --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A package for satellite image AI data prep
  home: https://github.com/forrestfwilliams/satchip
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forrestfwilliams
